compressionLevel: mixed

defaultSemverRangePrefix: ^

enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - checksum: 85c7634ccdff1dcd918d5c25e8746ca2f0098b22c1deea0bc4a4135f1e59f329d6e0abcfd27a8967df163e81cdd1f1d97dc3385dfe7ba17ccee2db8eaed32359
    path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: "https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/@yarnpkg/plugin-conventional-version.cjs"
