allowBuilds:
  esbuild: true
  unrs-resolver: true
dedupePeerDependents: true
nodeLinker: hoisted
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - "@pob/*"
  - pob-dependencies
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
  - alp-node-auth@13.1.0
  - alp-node@10.1.0
  - alp-rollup-plugin-config@4.1.0
  - router-segments@12.2.1
  - check-package-dependencies
  - error-html@0.4.1
packages:
  - packages/*
savePrefix: ^
